[package]
name = "maelstrom_distributed"
version = "0.1.0"
edition = "2021"

[dependencies]

serde = { version = "1", features = ["derive", "std", "alloc"], default-features = false }
serde_json = "1.0.134"
tracing = "0.1.41"
anyhow = "1"
